name: 'Failure Slack Message'
author: EleSangwon
description: 'Message that comes when the aws-chatbot fails'
inputs:
  MESSAGE: 
    description: 'Message sent when aws-chatbot job fails'
    required: true
    default: 'Chatbot '
  TYPE:
    required: true
    default: 'off'
  EKS_CLUSTER:
    required: true
    default: 'eks-cost-project-dev'
  TARGET_NAMESPACE:
    required: true
    default: 'sock-shop'
  TARGET_HELM:
    required: true
    default: 'sock-shop'
  SLACK_WEBHOOK:
    required: true
runs:
  using: "composite"
  steps:
    - name: Fail Message when aws-chatbot failed
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "attachments": [
                {
                    "fallback": "❌ ${{ inputs.MESSAGE }}",
                    "color": "#EB5353",
                    "text": "❌ Failure ${{ inputs.MESSAGE }}",
                    "fields": [
                        {
                            "title": "CLUSTER_NAME",
                            "value": "${{ inputs.EKS_CLUSTER }}",
                            "short": true
                        },
                        {
                            "title": "TARGET_NAMESPACE",
                            "value": "${{ inputs.TARGET_NAMESPACE }}",
                            "short": true
                        },
                        {
                            "title": "TARGET_HELM",
                            "value": "${{ inputs.TARGET_HELM }}",
                            "short": true
                        }
                    ]
                }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK