name: 'AWS Credential'
author: EleSangwon
description: 'Get AWS Credential using assume role'
inputs:
  AWS_REGION: 
    description: 'set aws region'
    required: false
    default: 'ap-northeast-2'
  AWS_ASSUME_ROLE:
    description: 'set assume role'
    required: true
    default: 'arn:aws:iam::123456789100:role/my-github-actions-role'
  AWS_ROLE_SESSIN_NAME:
    required: false
    default: 'eks-cost-project'
  AWS_ROLE_DURATION_SECONDS:
    required: false
    default: '1200'
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ASSUME_ROLE }}
        role-session-name: ${{ inputs.AWS_ROLE_SESSIN_NAME }}
        role-duration-seconds: ${{ inputs.AWS_ROLE_DURATION_SECONDS }}