name: 'Send Slack Message'
author: EleSangwon
description: ''
inputs:
  MESSAGE: 
    description: ''
    required: true
    default: ''
  TOTAL_BEFORE_COST: 
    description: ''
    required: true
    default: ''
  TOTAL_AFTER_COST: 
    description: ''
    required: true
    default: ''
  PR_URL:
    description: 'pr_url'
    required: true
    default: ''
  SAVING_PERCENT:
    description: ''
    required: true
    default: ''
  EKS_CLUSTER:
    required: true
    default: 'eks-cost-project-dev'
  TARGET_NAMESPACE:
    required: true
    default: 'sock-shop'
  TARGET_APP:
    required: true
    default: 'sock-shop'
  ACTION_URL:
    required: true
    default: 'sock-shop'
  SLACK_WEBHOOK:
    required: true
runs:
  using: "composite"
  steps:
    - name: Send Slack Message
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "attachments": [
                {
                    "fallback": "✅ ${{ inputs.MESSAGE }}",
                    "color": "#EB5353",
                    "text": "✅ ${{ inputs.MESSAGE }}",
                    "fields": [
                        {
                            "title": "CLUSTER_NAME",
                            "value": "${{ inputs.EKS_CLUSTER }}",
                            "short": true
                        },
                        {
                            "title": "SAVING_PERCENT",
                            "value": "${{ inputs.SAVING_PERCENT }} %",
                            "short": true
                        },
                        {
                            "title": "TOTAL_BEFORE_COST",
                            "value": "${{ inputs.TOTAL_BEFORE_COST }} USD",
                            "short": true
                        },
                        {
                            "title": "TOTAL_AFTER_COST",
                            "value": "${{ inputs.TOTAL_AFTER_COST }} USD",
                            "short": true
                        }
                    ],
                    "actions": [
                        {
                            "type": "button",
                            "text": "Visit PR",
                            "url" : "${{ inputs.PR_URL }}"
                        }
                    ]
                }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
